/**
 * Food Production Common API
 * Food Production Common API based on Reference Architectural Model Industrie 4.0 (RAMI 4.0)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnimalBeeCompositionInner, AnimalBeeCompositionInnerSchema } from './animalBeeCompositionInner';
import { Header, HeaderSchema } from './header';


export const AnimalSchema = {
  "type": "object",
  "properties": {
    "header": HeaderSchema,
    "beeComposition": AnimalBeeCompositionInnerSchema,
    "beeDensity": {
      "type": "number"
    },
    "beneficialInsectComposition": {
      "type": "number"
    },
    "harmfulInsectComposition": {
      "type": "number"
    },
    "diseasePrevalence": {
      "type": "number"
    },
    "microbialActivity": {
      "type": "number",
      "description": "mg/kg"
    }
  }
};


export interface Animal {
  'header'?: Header;
  'beeComposition'?: Array<AnimalBeeCompositionInner>;
  'beeDensity'?: number;
  'beneficialInsectComposition'?: number;
  'harmfulInsectComposition'?: number;
  'diseasePrevalence'?: number;
  /**
   * mg/kg
   */
  'microbialActivity'?: number;
};

