/**
 * Food Production Common API
 * Food Production Common API based on Reference Architectural Model Industrie 4.0 (RAMI 4.0)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AnimalBeeCompositionInnerSchema = {
    "type" : "array",
    "items" : {
        "type" : "object",
        "properties" : {
            "beeType" : {
                "type" : "string"
            },
            "beeTypePercentage" : {
                "type" : "number"
            }
        }
    }
}
export interface AnimalBeeCompositionInner {
    beeType?: string;
    beeTypePercentage?: number;

}

