/**
 * Food Production Common API
 * Food Production Common API based on Reference Architectural Model Industrie 4.0 (RAMI 4.0)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Header, HeaderSchema } from './header';

export const ConditionSchema = {
  "properties": {
    "header": HeaderSchema,
    "soilHumidity": {
      "description": "Volumetric water content",
      "format": "%",
      "maximum": 100,
      "minimum": 0,
      "type": "number"
    },
    "ph": {
      "maximum": 14,
      "minimum": 0,
      "type": "number"
    },
    "sunlight": {
      "format": "W/m^2",
      "type": "number"
    },
    "temperature": {
      "format": "°C",
      "type": "number"
    },
    "soilTemperature": {
      "type": "number",
      "description": "°C"
    },
    "waterDeficiency": {
      "type": "number"
    }
  },
  "type": "object"
};

export interface Condition {
  header?: Header;
  /**
   * Volumetric water content
   */
  soilHumidity?: number;
  ph?: number;
  sunlight?: number;
  temperature?: number;
  /**
   * °C
   */
  soilTemperature?: number;
  waterDeficiency?: number;
}

