/**
 * Food Production Common API
 * Food Production Common API based on Reference Architectural Model Industrie 4.0 (RAMI 4.0)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Header, HeaderSchema } from './header';

export const PrecipitationSchema = {
  "type": "object",
  "properties": {
    "header": HeaderSchema,
    "timing": {
      "format": "date-time",
      "type": "string"
    },
    "amount": {
      "type": "number"
    },
    "duration": {
      "type": "number"
    },
    "distribution": {
      "type": "string"
    },
    "evapotranspiration": {
      "type": "number"
    },
    "intensity": {
      "type": "string"
    },
    "variability": {
      "type": "string"
    },
    "daysSinceLastPrecipitation": {
      "type": "number"
    },
    "totalRainyDaysInSeason": {
      "type": "number"
    },
    "averageRainyDaysInSeason": {
      "type": "number"
    },
    "averagePotentialEvapotranspiration": {
      "type": "number"
    },
    "averageVaporPressureDeficit": {
      "type": "number"
    }
  }
};

export interface Precipitation {
  header: Header;
  timing?: Date;
  amount?: number;
  duration?: number;
  distribution?: string;
  evapotranspiration?: number;
  intensity?: string;
  variability?: string;
  daysSinceLastPrecipitation?: number;
  totalRainyDaysInSeason?: number;
  averageRainyDaysInSeason?: number;
  averagePotentialEvapotranspiration?: number;
  averageVaporPressureDeficit?: number;
}

