openapi: 3.0.3
info:
  description: |
    Food Production Common API based on Reference Architectural Model Industrie
    4.0 (RAMI 4.0)
  title: Food Production Common API
  version: 1.0.0
servers:
- url: http://localhost:8000/
paths:
  /soil/nutrients:
    get:
      responses:
        '200':
          description: 'Get Updated Nutrient Information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nutrient'

    post:
      summary: Soil nutrient measurement event
      description: |
          Raw sensor payment received in the integration layer and converted into 
          this common model to generate an event for the information layer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nutrient'
            examples:
              NutrientExample:
                $ref: '#/components/examples/NutrientExample'
          application/xml:
            schema:
              $ref: '#/components/schemas/Nutrient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Nutrient'
      responses:
        '201':
          description: Event successfully sent
      x-eov-operation-handler: controllers/DefaultController
  /soil/conditions:
    post:
      summary: Soil conditions measurement event
      description: |
        Raw sensor payment received in the integration layer and converted into 
        this common model to generate an event for the information layer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Condition'
          application/xml:
            schema:
              $ref: '#/components/schemas/Condition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Condition'
      responses:
        '201':
          description: Event successfully sent
      x-eov-operation-handler: controllers/DefaultController
  /soil/compositions:
    post:
      summary: Soil composition measurement event
      description: |
        Raw sensor payment received in the integration layer and converted into 
        this common model to generate an event for the information layer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition'
          application/xml:
            schema:
              $ref: '#/components/schemas/Composition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Composition'
      responses:
        '201':
          description: Event successfully sent
      x-eov-operation-handler: controllers/DefaultController
  /weather/temperature:
    post:
      summary: Soil composition measurement event
      description: |
        Raw sensor payment received in the integration layer and converted into 
        this common model to generate an event for the information layer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
          application/xml:
            schema:
              $ref: '#/components/schemas/Temperature'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Temperature'
      responses:
        '201':
          description: Event successfully sent
      x-eov-operation-handler: controllers/DefaultController
  /weather/precipitation:
    post:
      summary: Soil composition measurement event
      description: |
        Raw sensor payment received in the integration layer and converted into 
        this common model to generate an event for the information layer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Precipitation'
          application/xml:
            schema:
              $ref: '#/components/schemas/Precipitation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Precipitation'
      responses:
        "201":
          description: Event successfully sent
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Header:
      example:
        time: 2000-01-23T04:56:07.000+00:00
        farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        sensorId:
          format: uuid
          type: string
        time:
          format: date-time
          type: string
        fieldId:
          format: uuid
          type: string
        farmId:
          format: uuid
          type: string
      type: object
    Nutrient:
      example:
        potassium: 1.4658129805029452
        calcium: 5.962133916683182
        salt: 7.061401241503109
        nitrogen: 6.027456183070403
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        magnesium: 5.637376656633329
        sulfur: 2.3021358869347655
        iron: 3.616076749251911
        zinc: 9.301444243932576
        phosphorus: 0.8008281904610115
      properties:
        header:
          $ref: '#/components/schemas/Header'
        phosphorus:
          format: ppm
          type: number
        nitrogen:
          format: ppm
          type: number
        potassium:
          format: ppm
          type: number
        calcium:
          format: ppm
          type: number
        magnesium:
          format: ppm
          type: number
        sulfur:
          format: ppm
          type: number
        salt:
          description: |
            Soil salinity is measured in units of electrical conductivity (EC), which is also known as Siemens (S).
            The most common units of EC are deciSiemens per meter (dS/m)
          format: dS/m
          type: number
        cationExchangeCapacity:
          type: number
          description: |
            moving ions in the soil based on how much salt and how much water is in the soil.
        zinc:
          format: ppm
          type: number
        iron:
          format: ppm
          type: number
        nutrientDeficiency:
          type: array
          items:
            type: string
      type: object
    Composition:
      example:
        heavyMetals: 6.027456183070403
        organicMass: 8.008281904610115
        granularity: 5.962133916683182
        soilType: Gravel
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        microbialActivity: 1.4658129805029452
      properties:
        header:
          $ref: '#/components/schemas/Header'
        organicMass:
          description: biomass as a % of soil
          format: '%'
          maximum: 100
          minimum: 0
          type: number
        heavyMetals:
          format: ug/kg or ppb
          type: number
        microbialActivity:
          format: mg/kg
          type: number
        granularity:
          description: |
            Percentage of fine grains to weight
            Higher percentage of file grains means the soil is more cohesive (more clay).
            Lower % of fine grains mean the soil is more granular
          format: '%'
          type: number
        soilType:
          description: |
            Gravel: >2.0mm
            Very coarse: 1.0 - 2.0mm
            Coarse: 0.50 - 1.0mm
            Medium: 0.25 - 0.50mm
            Fine: 0.10 - 0.25mm
            Very fine: 0.05 - 0.10mm
          enum:
          - Gravel
          - Very coarse
          - Coarse
          - Medium
          - Fine
          - Very fine
          type: string
      type: object
    Condition:
      example:
        sunlight: 1.4658129805029452
        ph: 8.438438656298565
        temperature: 5.962133916683182
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        soilHumidity: 8.008281904610115
      properties:
        header:
          $ref: '#/components/schemas/Header'
        soilHumidity:
          description: Volumetric water content
          format: '%'
          maximum: 100
          minimum: 0
          type: number
        ph:
          maximum: 14
          minimum: 0
          type: number
        sunlight:
          format: W/m^2
          type: number
        temperature:
          format: °C
          type: number
        soilTemperature:
          type: number
          description: °C
        waterDeficiency:
          type: number
      type: object
    Temperature:
      example:
        duration: 6.027456183070403
        level: 0.8008281904610115
        timing: 2000-01-23T04:56:07.000+00:00
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        header:
          $ref: '#/components/schemas/Header'
        timing:
          format: date-time
          type: string
        dailyAirTemperature:
          type: number
          description: maximum air temperature of the day in Celsius
        duration:
          type: number
        minimalAirTemperatureSeason:
          type: number
          description: minimum air temperature recorded during the growing season in Celius .
        maximumAirTemperatureSeason:
          type: number
          description: maximum air temperature recorded during the growing season in Celius .
        averageAirTemperatureSeason:
          type: number
          description: average air temperature recorded during the growing season in Celius .
        growingDegreeDays:
          type: number
          description: number of days in the seasons above the growing threshold for the crop.
      type: object
    Precipitation:
      example:
        duration: 6.027456183070403
        intensity: intensity
        amount: 0.8008281904610115
        timing: 2000-01-23T04:56:07.000+00:00
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        distribution: distribution
        variability: variability
        evaporation: 1.4658129805029452
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        timing:
          format: date-time
          type: string
        amount:
          type: number
        duration:
          type: number
        distribution:
          type: string
        evapotranspiration:
          type: number
        intensity:
          type: string
        variability:
          type: string
        daysSinceLastPrecepitation:
          type: number
        totalRainyDaysInSeason:
          type: number
        averageRainyDaysInSeason:
          type: number
        averagePotentialEvapotranspiration:
          type: number
        averageVaporPresureDeficit:
          type: number
    Plant:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        weedSpatialOccurance:
          type: number
          description: average distance
        plantSpatialArrangement:
          type: number
          description: average distance
        outcrossingAndSelfPollination:
          type: string
          enum: [ CROSS, SELF, BOTH ]
        cloneSize:
          type: number
        fruitSet:
          type: number
          description: days
    Animal:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/Header'
        beeComposition:
          type: array
          items:
            type: object
            properties:
              beeType:
                type: string
              beeTypePercentage:
                type: number
        beeDensity:
          type: number
        beneficialInsectComposition:
          type: number
        harmfulInsectComposition:
          type: number
        diseasePrevalence:
          type: number
        microbialActivity:
          type: number
          description: mg/kg
  examples:
    NutrientExample:
      value: {
        "header": {
          "sensorId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "time": "2024-03-27T17:33:31.482Z",
          "fieldId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        },
        "phosphorus": 5,
        "nitrogen": 12,
        "potassium": 8,
        "calcium": 8,
        "magnesium": 5,
        "sulfur": 1,
        "salt": 12,
        "zinc": 2,
        "iron": 4
      }


